/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    skills: Skill;
    experience: Experience;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    experience: ExperienceSelect<false> | ExperienceSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    hero: Hero;
    'now-bar': NowBar;
    about: About;
    contact: Contact;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    'now-bar': NowBarSelect<false> | NowBarSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Lower number = shown first
   */
  order?: number | null;
  /**
   * Show this project in the featured spotlight
   */
  featured?: boolean | null;
  /**
   * e.g. 001, 002, 003
   */
  num: string;
  type: 'platform' | 'tool' | 'fullstack' | 'ml' | 'finance' | 'mobile' | 'design' | 'other';
  year: string;
  title: string;
  /**
   * The italic/highlighted part of the project title
   */
  titleEm: string;
  /**
   * One-line summary shown on card
   */
  sub: string;
  /**
   * Full description shown in featured view
   */
  desc: string;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  liveUrl?: string | null;
  githubUrl?: string | null;
  /**
   * Large decorative text/emoji shown in visual area (e.g. 3D, TS, ₿)
   */
  visLabel?: string | null;
  /**
   * Small caption under the visual (e.g. interactive · collab)
   */
  vcText?: string | null;
  /**
   * Tech stack flow diagram rows
   */
  architecture?:
    | {
        /**
         * e.g. data, realtime, deploy
         */
        label: string;
        boxes?:
          | {
              tech: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Slides shown in the featured project visual area
   */
  slides?:
    | {
        label: string;
        /**
         * Upload a screenshot. If empty, uses color/icon fallback.
         */
        image?: (number | null) | Media;
        /**
         * Hex color for fallback visual (e.g. #2d3561)
         */
        color?: string | null;
        /**
         * Hex color for slide background (e.g. #eaeaf8)
         */
        bg?: string | null;
        /**
         * Symbol shown when no image uploaded
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: number;
  name: string;
  /**
   * Auto-filled by the icon picker above. You can also type a simpleicons.org slug manually.
   */
  iconSlug?: string | null;
  /**
   * Auto-filled by the icon picker. Brand hex color, e.g. #61DAFB.
   */
  iconColor?: string | null;
  category: 'frontend' | 'backend' | 'database' | 'devops' | 'tools' | 'languages' | 'mobile' | 'ai_ml';
  /**
   * Mark skills you are actively using right now.
   */
  hot?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience".
 */
export interface Experience {
  id: number;
  /**
   * Lower number = shown first
   */
  order?: number | null;
  company: string;
  /**
   * Logo shown next to the company name
   */
  companyLogo?: (number | null) | Media;
  /**
   * e.g. Remote · Pakistan, or Lahore, Pakistan
   */
  location?: string | null;
  role: string;
  employmentType?: ('full-time' | 'part-time' | 'internship' | 'contract' | 'freelance') | null;
  /**
   * e.g. Dec 2025, Jul 2024
   */
  startDate: string;
  /**
   * Leave blank if currently working here
   */
  endDate?: string | null;
  current?: boolean | null;
  /**
   * Short summary of your work there
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'skills';
        value: number | Skill;
      } | null)
    | ({
        relationTo: 'experience';
        value: number | Experience;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  order?: T;
  featured?: T;
  num?: T;
  type?: T;
  year?: T;
  title?: T;
  titleEm?: T;
  sub?: T;
  desc?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  liveUrl?: T;
  githubUrl?: T;
  visLabel?: T;
  vcText?: T;
  architecture?:
    | T
    | {
        label?: T;
        boxes?:
          | T
          | {
              tech?: T;
              id?: T;
            };
        id?: T;
      };
  slides?:
    | T
    | {
        label?: T;
        image?: T;
        color?: T;
        bg?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  name?: T;
  iconSlug?: T;
  iconColor?: T;
  category?: T;
  hot?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience_select".
 */
export interface ExperienceSelect<T extends boolean = true> {
  order?: T;
  company?: T;
  companyLogo?: T;
  location?: T;
  role?: T;
  employmentType?: T;
  startDate?: T;
  endDate?: T;
  current?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  tagline?: string | null;
  status?: ('available' | 'busy' | 'open to offers') | null;
  location?: string | null;
  timezone?: string | null;
  /**
   * Small version label shown in nav (e.g. v1.0)
   */
  navVersion?: string | null;
  /**
   * 6-char git hash shown in nav. Update manually or via CI.
   */
  lastCommit?: string | null;
  githubUrl?: string | null;
  linkedinUrl?: string | null;
  readcvUrl?: string | null;
  /**
   * Tech chips shown in the Now Bar strip (e.g. TypeScript, Next.js)
   */
  nowBarChips?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  /**
   * Small text above the name (e.g. "available for work")
   */
  eyebrow?: string | null;
  firstName: string;
  role: string;
  bio: string;
  /**
   * Key-value lines shown in the terminal-style sys box
   */
  sysBoxLines?:
    | {
        key: string;
        value: string;
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Text in the "currently building" bar below the hero
   */
  nowBarText?: string | null;
  /**
   * Small stats shown in the hero bottom bar (e.g. projects, experience)
   */
  statsBar?:
    | {
        /**
         * e.g. 5+
         */
        value: string;
        /**
         * e.g. projects shipped
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "now-bar".
 */
export interface NowBar {
  id: number;
  /**
   * Small prefix label (e.g. "currently building")
   */
  label?: string | null;
  text: string;
  link?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  bio1?: string | null;
  bio2?: string | null;
  image?: (number | null) | Media;
  /**
   * Key-value facts shown in the about section grid
   */
  facts?:
    | {
        /**
         * e.g. based_in, experience, focus
         */
        key: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The numbered process steps shown below the bio
   */
  processSteps?:
    | {
        /**
         * e.g. 01, 02, 03
         */
        number: string;
        title: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  subtext?: string | null;
  email: string;
  responseTime?: string | null;
  availability?: ('open' | 'busy' | 'closed') | null;
  preferredWork?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  status?: T;
  location?: T;
  timezone?: T;
  navVersion?: T;
  lastCommit?: T;
  githubUrl?: T;
  linkedinUrl?: T;
  readcvUrl?: T;
  nowBarChips?:
    | T
    | {
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  eyebrow?: T;
  firstName?: T;
  role?: T;
  bio?: T;
  sysBoxLines?:
    | T
    | {
        key?: T;
        value?: T;
        highlight?: T;
        id?: T;
      };
  nowBarText?: T;
  statsBar?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "now-bar_select".
 */
export interface NowBarSelect<T extends boolean = true> {
  label?: T;
  text?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  bio1?: T;
  bio2?: T;
  image?: T;
  facts?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  processSteps?:
    | T
    | {
        number?: T;
        title?: T;
        desc?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subtext?: T;
  email?: T;
  responseTime?: T;
  availability?: T;
  preferredWork?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}